### ISSUE TITLE
head files to wrong dir

### ISSUE THREAD

**Issue by yangming** [agordon/libgtextutils#4]
.h files are installed to /usr/include/gtextutils/gtextutils/
in gtextutils.pc file, the Cflags is  -I${includedir}/gtextutils, which will find head files at /usr/include/gtextutils, not the subdir.

in this senario, complilation of fastx_uncollapser.cpp will be terminated with fatal error: gtextutils/stream_wrapper.h: no such file.
in fastx_uncollapser.cpp, the include line is #include <gtextutils/stream_wrapper.h>, not <gtextutils/gtextutils/wrapper.h>

**Comment by agordon** [comment]
Hello,

Thank you for your post. However, you scenario is incorrect: the `#include` statement in `fastx_uncollaspter.cpp` contains the additional subdirectory, so there are no compilation issues.

regards,
-assaf
