### ISSUE TITLE
Where is the INSTALL file?

### ISSUE THREAD

**Issue by molecules** [agordon/libgtextutils#7]
I couldn't find the fille named "INSTALL", but found mention of it in the .gitignore file. So, am I correct that it hasn't be uploaded and we can't see it?

Thanks!

**Comment by agordon** [comment]
No, that is not accurate.

The `INSTALL` file is automatically added by GNU-autotools when you run `recent` (or `autoreconf -if`).
It is not (and should not be) included in the git repository.
Alternatively, the file is included in the tarball in the *Releases* page ( https://github.com/agordon/libgtextutils/releases ).

regards,
  assaf
