### ISSUE TITLE
There is no INSTALL file

### ISSUE THREAD

**Issue by jarekbryk** [agordon/libgtextutils#8]
Hi, there is no INSTALL file even though it is mentioned in the README.

**Comment by bgruening** [comment]
ping @agordon

**Comment by joshgraymd** [comment]
ping @agordon

**Comment by agordon** [comment]
There is no INSTALL file on purpose. It will be auto-generated when running ./reconf .
This is how autotools packages work.

To learn more, please see past discussions:
https://github.com/agordon/fastx_toolkit/issues/10
https://github.com/agordon/fastx_toolkit/issues/8
https://github.com/agordon/fastx_toolkit/issues/11
